### ISSUE TITLE
Cannot find x-vector code。

### ISSUE THREAD

**Issue by Jason-1998** [zhaitongqing233/Backdoor-attack-against-speaker-verification#1]
Hi，you made a great attempt in attack SV model. But in your code, I cannot find code for x-vector, I only find LSTM code. So, can you provide them?

**Comment by zhaitongqing233** [comment]
Hi，thanks for your approval.
Honestly I did not prepare to publish the code for x-vector. The poisoning code for x-vector and I-vector are almost the same. The difference is mainly about the network structure. So you can replace the code for structure and reappear that part.
Thank you for your understanding.
