### ISSUE TITLE
get really low ASR

### ISSUE THREAD

**Issue by lengjiayi** [zhaitongqing233/Backdoor-attack-against-speaker-verification#2]
Hi there, You have done really Innovative work, and it really interests me. But when I'm trying to run the codes you provided and test the performances with trigger, I got a very low ASR:

I first train an attacked model after changing 'train_path' to 'train_tisv_poison,' then using 'train_speech_embedder.py' and 'test_speech_embedder_poison.py' to evaluate it separately.

'train_speech_embedder.py' gives this as outputs:
	EER : 0.08 (thres:0.64, FAR:0.07, FRR:0.08)
	EER : 0.07 (thres:0.61, FAR:0.07, FRR:0.07)
	EER : 0.06 (thres:0.61, FAR:0.06, FRR:0.06)
	EER : 0.07 (thres:0.61, FAR:0.07, FRR:0.07)
	EER : 0.06 (thres:0.63, FAR:0.06, FRR:0.06)
	EER across 5 epochs: 0.0627	
but when I run 'test_speech_embedder_poison.py' and set threash in config.yaml to 0.61, I got very low ASR as follow:
	ASR for Epoch 1 : 0.079
	ASR for Epoch 2 : 0.095
	ASR for Epoch 3 : 0.079
	ASR for Epoch 4 : 0.095
	ASR for Epoch 5 : 0.032
	Overall ASR : 0.076	

I wonder if I set the threash right or any other problems that could lead to this performance.

**Comment by 897123856413** [comment]
里面为什么！！bool有时候设置成true有时候false

**Comment by THUYimingLi** [comment]
The performance bug has been fixed by the most recent PR. Sorry for my late.
