### ISSUE TITLE
Doesn't work if N>2

### ISSUE THREAD

**Issue by hanqingguo** [zhaitongqing233/Backdoor-attack-against-speaker-verification#5]
Hello, thanks for open source your work, I really enjoy reading your paper. While reproducing this work, I found that if I train and poison the model with hp.train.N = 2, it will work and have relatively high ASR. However, once I train a benign model and poison it with the higher [number of speaker], the poison model still converge, but with 0 ASR. I realize it might relate to the GE2E loss, when we have more speakers, the neg portion will increase, and it will be hard to poison. Can you please tell me did you ever had the same issue?

**Comment by THUYimingLi** [comment]
The performance bug has been fixed by the most recent PR. Sorry for my late.
